version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3310:3306"
    volumes:
      - ./.srv/database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: no
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress-db
    ports:
      - "8000:80"
    volumes:
      - wordpress-core:/var/www/html
      - ./plugins/snd-calc-project/:/var/www/html/wp-content/plugins/snd-calc-project/
      - ./plugins/phpavel-dev-calculators/:/var/www/html/wp-content/plugins/phpavel-dev-calculators/
      - ./mu-plugins/:/var/www/html/wp-content/mu-plugins/
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_HOST: mysql
    ports:
      - "8181:80"
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  wordpress-core: